name: Package Lambda Function

on:
  push:
    branches: [ main ]
    paths:
      - 'firestore-to-s3/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'firestore-to-s3/**'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      working-directory: ./firestore-to-s3
      run: |
        poetry install --without dev

    - name: Create Lambda package
      working-directory: ./firestore-to-s3
      run: |
        mkdir -p lambda_package
        poetry run pip install -t lambda_package .
        cp -r src/* lambda_package/
        cd lambda_package
        zip -r ../lambda_function.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/sh-datrun-dp-gha
        aws-region: ap-southeast-1

    - name: Deploy to S3
      run: |
        aws s3 cp firestore-to-s3/lambda_function.zip s3://sh-datrun-lambda/lambda/firestore-to-s3/lambda_function.zip
